blank_issues_enabled: false
contact_links:
  - name: Official documentation
    url: http://glassthought.com/
    about: Check our documentation for guides and gotchas.
  - name: Thorg Discord community
    url: https://discord.gg/YGthSxfu 
    about: Join our discord to connect with users and devs, and hear about the latest updates.



    
