blank_issues_enabled: false
contact_links:
  - name: Official documentation
    url: TODO
  - name: Thorg Discord community
    url: https://discord.gg/YGthSxfu 
  - name: Thorg support email
    url: TODO
    about: Contact us directly if your issue contains sensitive information.



    